SalesAssistant/Seller/urls.py
from django.urls import path
import random
import string


# ========== import form current app =========
from . import views as main_views

# ================ set app's name =============
app_name = "seller"
def random_generator():
    return random.choices(string.ascii_uppercase[:10])


call_it = random_generator()
# ================ config urls with views ===========================
urlpatterns = [
    # ================= url patterns ================================
    # home
    path('',main_views.index_page,name="home"),
    # add to stock

    path('add-to-stock/',main_views.add_to_stock,name="add-to-stock"),
    path('add/category/',main_views.add_category,name='category'),
    path('expenses',main_views.set_expenses,name="expenses"),
    # profile

    path('profile/',main_views.profile,name="profile"),
    path('product/editor/<int:product_id>/edit',main_views.edit_product_info,name="edit_product"),
    path('delete/item-number/<int:item_id>-from/database',main_views.delete_product,name="delete-item"),
    
    # orders
    path('my/order/',main_views.myOrders,name="my-orders"),
    path('clear/my/orders',main_views.clear_orders,name="clear-orders"),
    path('add/<int:product_id>to/cart',main_views.add_to_cart,name="add-to-cart"),
    
    # search
    path('searched/results/',main_views.search_product,name='search-results'),
    path('show/<int:productId>/detailed-description/',main_views.show_product_description,name='show-description'),
]

SalesAssistant/salesAPI/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('',include("Seller.urls")),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SalesAssistant/Seller/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class ProductType(models.Model):
    """ model of products at shop"""
    type_name = models.CharField("Product Type:",max_length=50,null=False)


    class Meta:
        verbose_name_plural = "Product Type"

    def __str__(self):
        """ string representation of the product type"""
        return self.type_name



class Product(models.Model):
    """ individual products in the shop """
    product_type = models.ForeignKey(ProductType,on_delete=models.CASCADE)
    product_name = models.CharField("Product Name:",max_length=25)
    price = models.DecimalField("Product Price:",max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to="images/%Y/%m/%d")
    number_of_products = models.IntegerField("No. of Products:",default=0)
    stock_date = models.DateTimeField("Stock Date",auto_now_add=True)
    manuf_date = models.DateField('Manuf. Date:',auto_now_add=False)
    expire_date = models.DateField('Expire Date:',auto_now_add=False)
    description = models.TextField('Description',blank=True,null=True)


    class Meta:
        ordering = ("expire_date",)
        verbose_name_plural = ("Products")
    
    def __str__(self):
        """ string representation of the product name"""
        return self.product_name
    
    def date_has_expire(self):
        """ 
        return true if date has expire and ask to delete item
        Return True if expire date is less than today's date.
        """
        return self.expire_date <= datetime.today()

    def product_status(self):
        """return the number of products remained in the stock"""
        return self.number_of_products


class Sales(models.Model):
    """products soled in a day"""
    BOUGHT_BY =(
        ('c',"Cash"),('mm',"Mobile Money"),('o',"Others"),
        )
    product_Name = models.CharField("Product Name",max_length=25,null=False)
    amount = models.DecimalField(verbose_name="Amount",max_digits=18,decimal_places=2)
    date_purchased = models.DateTimeField(verbose_name="Date Purchased",auto_now_add=True)
    number_purchased = models.IntegerField(verbose_name="Number Purchased",default=0)
    mode_of_payment = models.CharField("Mode of Payment",choices=BOUGHT_BY,max_length=10)
    purchase_by = models.CharField("Client Name",max_length=25,null=False)
    phone = models.CharField("Phone",max_length=15,null=True)

    def __str__(self):
        return self.product_Name
    

class Orders(models.Model):
    product_name = models.CharField("Product Name",max_length=25,null=True)
    price = models.DecimalField("Price",decimal_places=2,max_digits=18)
    number_purchase = models.IntegerField("Number Bought",default=0)
    date_order = models.DateTimeField("Order Date",auto_now_add=True)

    def __str__(self):
        return self.product_name

SalesAssistant/Seller/forms.py
from django import forms

from .models import Product,ProductType

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "product_type",
            ]

class ProductTypeForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = [
            "type_name",
            ]

SalesAssistant/Seller/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.core.validators import ValidationError
from django.db.models import Q
from django.contrib import messages



#============== import from current app ================
from .models import Product,ProductType,Orders
from .forms import ProductForm,ProductTypeForm
from . import orders,total


# Create your views here.
# =================== display all products in the shop ==========================
def index_page(request):
    product_type = Product.objects.order_by('expire_date').all()
    # product = product_type.producttype_set.all()
    context={"products":product_type}
    return render(request,'Seller/index.html',context)

# ==================== search product in the shop ==================
def search_product(request):
    """ user enters the name of the product to search"""

    item_property = request.POST['search']
    #search here
    products = Product.objects.filter(
                                        Q(product_name__icontains=item_property)|
                                        Q(price__icontains=item_property)|
                                        Q(product_type__type_name__icontains=item_property)
                                    ).order_by("-expire_date").all()
    context = {
        "products":products,
        "item":item_property,
        }
    return render(request,"Seller/search_results.html",context)

# ====================== add product to database =====================
def add_to_stock(request):
    """ add product type and the product to stock"""
    product_Type = ProductType.objects.all()
    # current_trip = Trip.objects.filter("-date_added").all()
    # context = {"trip":current_trip,}
    if request.method == "POST":
        # user has restock the shop
        form = ProductForm(request.POST)

        product_name = request.POST['productName']
        product_price = request.POST['price']
        productsnumber = request.POST["numberofproducts"]
        mandate = request.POST['manuf_date']
        expiredate = request.POST['expire_date']
        filesimage=request.FILES['product_image']
        product_description = request.POST["description"]
        productform = Product(product_name=product_name,price=product_price,
                                number_of_products=productsnumber,manuf_date=mandate,
                                expire_date=expiredate,image=filesimage,description=product_description)
        # return form with data
        try:
            if form.is_valid():
                product = form.save(commit=False)
                productform.product_type = product.product_type
                productform.save()
                # valid data has been provided
                return redirect("seller:home")
        except ValidationError:
            pass
    else:
        form = ProductForm()
    context = {
        "items":product_Type,
        "form":form,
        # "trip":current_trip,
    }
    
    return render(request,"Seller/add_product.html",context)

# ================== store product buy category ================
def add_category(request):
    """add catergoty of products sell by shop"""
    if request.method == "POST":
        # post the data
        form = ProductTypeForm(data=request.POST)
        # validate the data
        if form.is_valid():
            form.save()
            # go add add the products
            return redirect("seller:expenses")
    else:
        # render empty form
        form = ProductTypeForm()
    context = {
        "form":form
    }
    return render(request,"Seller/add_category.html",context)

#  ============================ set expenses during buying of produts===================
def set_expenses(request):
    """add expenses that took in buying the products"""
    
    if request.method == "POST":
        # name = request.POST["TripName"]
        # amount= request.POST["amount"]
        # other = request.POST["others"]
        # trip = Trip(trip_name=name,purchases_total=amount,other_charges=other)
        # trip.save() 
        return redirect("seller:category")
    
    return render(request,"Seller/expense.html")

# ======================== profile of the seller ======================
def profile(request):
    """ User profile informations"""
    myProducts = Product.objects.all()
    context = {
        "products":myProducts,
    }
    return render(request,"Seller/profile.html",context)

# ========================delete product from database===========================
def delete_product(request,item_id):
    """delete the product from database"""
    product_to_remove = get_object_or_404(Product,pk=item_id)
    product_to_remove.delete()
    return redirect("seller:profile")

# ====================== edit product information ========================
def edit_product_info(request,product_id):
    """ edit the mistakes of the product information"""
    product = get_object_or_404(Product,pk=product_id)
    if request.method == "POST":
        edited_product_name = request.POST['productName']
        edited_product_price = request.POST['price']
        edited_productsnumber = request.POST["numberofproducts"]
        edited_mandate = request.POST['manuf_date']
        edited_expiredate = request.POST['expire_date']
        edited_filesimage=request.FILES['product_image']
        edited_product_description = request.POST["description"]
        productform = Product(
            product_name=edited_product_name,price=edited_product_price,
            number_of_products=edited_productsnumber,manuf_date=edited_mandate,
            expire_date=edited_expiredate,image=edited_filesimage,description=edited_product_description
            )
        productform.product_type = product.product_type
        productform.save()
        return redirect("seller:profile")
    context={
        "product":product,
    }
    return render(request,'Seller/edit_product_info.html',context)

# ============================== show product description =======================================
def show_product_description(request,productId):
    """ show the detailed description of the product"""
    product_description = get_object_or_404(Product,pk=productId)
    context={
        "product":product_description,
    }
    return render(request,'Seller/show_description.html',context)

# ================== add to cart =====================================
def add_to_cart(request,product_id):
    """add product to cart"""
    product = get_object_or_404(Product,pk=product_id)
    if request.method == "POST":
        number = int(request.POST["number_to_buy"])
        # add the item to
        current_number = product.number_of_products
        if current_number < number:
            messages.error(request,f"{current_number} is less than {number}. Enter a less or equal number")
        else:
            if number>=1:

                name = product.product_name
                price = float(product.price)
                total['total_price'] += price* number
                orders.append({"product":name,"number":number,
                    "price":price,"id":product.id
                })
                return redirect("seller:home")
            messages.warning(request,"Invalid Input")
    context = {
        "product":product,
    }
    return render(request,'Seller/orders.html',context)
        
# ================================ my order to buy ===============================
def myOrders(request):
    """ buy bulk items"""
    " get the product to buy and the bought product"""
    # get the product by its id
    if request.method == "POST":
        # the customer bought the product
        customer_name = request.POST["customer_name"]
        customer_email = request.POST["customer_email"]
        if len(orders) > 0:
            buy_ordered_products(request)
            messages.success(request, customer_name+" "+ customer_email +" Thanks For Buying From Us. See You Next Time.")
            clear_orders(request)
            return redirect("seller:my-orders")
        else:
            messages.error(request,"Orders Must Not Be Empty")
    context = {
        "orders_number":orders.__len__(),
        "orders":orders,
        "total":total,

    }
    return render(request,'Seller/myOrders.html',context)

# ============================= buy ordered products ==============================
def buy_ordered_products(request):
    """ process all items to buy"""
    for item in orders:
        boughts = item["number"]
        product_id = item["id"]
        product_bought = get_object_or_404(Product,pk=product_id)
        # remove the number of products bought from the stock
        # at the time of buying if orders is greater than number to buy 
        at_buy_number = product_bought.number_of_products
        if at_buy_number >= int(boughts):
            try:
                product_bought.number_of_products -= int(boughts)
                # save the remaining to the stock
                product_bought.save()
            except ValueError:
                pass
        else:
            messages.error(request,"Your Resquests Are More Than Stock Products")

# ============================== clear orders============================
def clear_orders(request):
    """ clear orders"""
    total['total_price'] = 0.0
    orders.clear()
    return redirect("seller:my-orders")

SalesAssistant/Seller/templates/Seller/add_category.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %} Category {% endblock title %}
<!--  -->
{% block content %}
<!--  -->
<div class="catergory-title">
    <h3>Add Item's Category</h3>
</div>
<form action=" {% url 'seller:category' %}" method="POST" class="category-form">
    {% csrf_token %}
    <div>
        Add Category: {{form.type_name}}
    </div>
    <div>
        <input class="category-btn" type="submit" value="Submit" />
    </div>

</form>
<div class="add-link">
    <a href="{% url 'seller:add-to-stock' %}">Add Product</a>
</div>
<!--  -->
{% endblock content %}

SalesAssistant/Seller/templates/Seller/add_product.html
{% extends 'Seller/base.html' %}
<!-- extend base html from parent -->
{% load crispy_forms_tags %}
<!-- load crispy form tags -->

{% block title %} add product {% endblock title %}
<!-- title -->



<!-- body content -->

{% block content %}
<div class="product-info">
    <form action="{% url 'seller:add-to-stock' %}" method="POST" class="product-form" onSubmit="doOnSubmit()" enctype="multipart/form-data">
        {% csrf_token %}
        <!--  -->
        <div>{{form.as_p}}</div>
        <!--  -->
        <div>
            <p>Product Name:</p>
            <input id="productName" type="text" name="productName" placeholder="Enter Product Name" required/>
            <!--  -->
        </div>
        <div>
            <!-- -->
            <p>No. of Products: </p>
            <input id="nproducts" type="number" name="numberofproducts" placeholder="Number of Products" />

        </div>
        <div>
            <p>Purchase At:</p>
            <input id="priceInput" type="number" name="unitPrice" oninput="doOnChange()" placeholder="Enter Purchase Price" required/>

        </div>
        <!--  -->
        <div>
            <p>Manuf. Date:</p>
            <input type="date" name="manuf_date" placeholder="01-02-1996" />
        </div>
        <!--  -->
        <div>
            <p>Expire Date:</p>
            <input type="date" name="expire_date" placeholder="02-01-1996" />
            <!--  -->
        </div>
        <!--  -->


        <div>
            <p>Photo:</p>
            <input type="file" name="product_image" required/>
            <!--  -->
        </div>



        <!--  -->
        <div>
            </p>Current Pricing</p>
            <input id="cprice" name="price" oninput="doOnChange()" placeholder="current princing" />
        </div>

        <div>
            <!--  -->
            <p>Description</p>
            <textarea name="description" id="for-product-description" cols="30" rows="10" placeholder="Add Description"></textarea>
        </div>

        <button class="btn btn-primary">Submit</button>
    </form>

    <!--  -->
    <div class="sales-info">
        <h4>Current Product Information</h4>
        <hr>
        <p>Product Name: <strong></strong><span id="product_name"></span></strong>
        </p>
        <p>Cost Price: &cent;<span id="costPrice"></span></p>
        <p>Selling Price: &cent;<span id="sellingPrice"></span></p>
        <p>Percentage Charge: &percnt; <span id="percent"></span></p>
        <p>Profit &cent; <span id="profit"></span></p>
    </div>
</div>
<section class="section-link">
    <a href="{% url 'seller:category' %}">Add Category First.</a>
</section>



{% endblock content %}

SalesAssistant/Seller/templates/Seller/base.html
<!DOCTYPE html>
<!--  -->
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title> {% block title %}{% endblock title %} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="online shop manager,sales assistant, auto generate prices of goods,auto pricer" />
    <meta name="author" content="KONJA KUMA SAMPSON,prof86k,Dr.Ksp-virus" />
    <link rel="stylesheet" type="text/css" href="{% static '/seller/css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/seller/css/cat_and_add.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static '/seller/css/main_page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'seller/css/sales_and_orders.css' %}" />
    <!--  -->

    {% include "Seller/navbars.html" %}
    <!--  -->
    {% load crispy_forms_tags %}
</head>

<body>
    <div id="main-content">
        <div>
            <div class="container-items">
                <form action="{% url 'seller:search-results' %}" method="POST" class="search-form">
                    {% csrf_token %}
                    <input type="text" name="search" placeholder="eg. product name ,price or category" required/>
                    <button class="search-btn">Search</button>
                </form>
            </div>
            <marquee>Welcome To Seller </marquee>
            <div class="web-logo">
                <h1> mASTER mARKET</h1>
                <hr style="border:2px solid red">
            </div>

            {% block content %}{% endblock content %}
        </div>
    </div>
    <hr class="hr-above-footer">
    <section>
        <footer>
            <section class="comments-section">
                <h3>Leave Your Comments Here</h3>
                <form>
                    {% csrf_token %}
                    <input type="email" name="email" placeholder="Email" required />
                    <textarea name="comments" id="com" placeholder="Comment here" required></textarea>
                    <input type="submit" value="Comment" />
                </form>
            </section>
            {% include 'Seller/footer_links.html' %}
        </footer>
    </section>
    <script language="javascript" type="text/javascript" src="{% static '/seller/js/salesInput.js' %}"></script>
    <!-- <script language="javascript" type="text/javascript" src="{% static '/js/popupForm.js' %}"></script> -->
</body>

</html>

SalesAssistant/Seller/templates/Seller/edit_product_info.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %}{% endblock title %}
<!--  -->

{% block content %}
<!--  -->
<div class="edit-product-info" style="margin:20px;">
    <h3>Edit {{product.product_name}} Information</h3>
    <form action="{% url 'seller:edit_product' product.id %}" class="product-edit-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <p>Product Name:</p>
            <input id="productName" type="text" name="productName" value="{{product.product_name}}" required/>
            <!--  -->
        </div>
        <div>
            <!-- -->
            <p>No. of Products: </p>
            <input id="nproducts" type="number" name="numberofproducts" value="{{product.number_of_products}}" />

        </div>
        <div>
            <p>Purchase At:</p>
            <input id="priceInput" type="number" name="unitPrice" oninput="doOnChange()" placeholder="Enter Purchase Price" />

        </div>
        <!--  -->
        <div>
            <p>Manuf. Date:</p>
            <input type="date" name="manuf_date" value="{{product.manuf_date}}" /> {{product.manuf_date}}
        </div>
        <!--  -->
        <div>
            <p>Expire Date:</p>
            <input type="date" name="expire_date" value="{{product.expire_date}}" /> {{product.expire_date}}
            <!--  -->
        </div>
        <!--  -->


        <div>
            <p>Photo:</p>
            <input type="file" name="product_image" required/> <img src="{{product.image.url}}" width="50px " height="50px" />
            <!--  -->

        </div>
        <!--  -->
        <div>
            </p>Current Pricing</p>
            <input id="cprice" name="price" oninput="doOnChange()" value="{{product.price}}" />
        </div>

        <div>
            <!--  -->
            <p>Description</p>
            <textarea name="describe" id="for-product-description" cols="30" rows="10">{{product.description}}"</textarea>
        </div>

        <!--  -->
        <input type="submit" value="Save" />

    </form>
</div>

<!--  -->

{% endblock content %}

SalesAssistant/Seller/templates/Seller/expense.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %} Category{% endblock title %}
<!--  -->
{% block content %}
<!--  -->
<div class="popup-form" id="expenseForm">
    <form action=" {% url 'seller:expenses' %}" onSubmit="doSaveTransport()" method="POST" class="form-box">
        {% csrf_token %}
        <!--  -->
        <div>
            <input id="tamount" type="number" name="amount" placeholder="Total Amount" required/>
        </div>
        <!--  -->
        <div>
            <input id="tothers" type="number" name="others" placeholder="Other Charges" required/>
        </div>
        <!--  -->
        <div>
            <input class="btn" type="submit" value="Submit" />
        </div>
    </form>
    <section class="linkers">
        <p>
            <small>
                Add Products Types <small><a href="{% url 'seller:category' %}">Category</a></small>
            </small>
        </p>
        <p>
            <small>
                Select Category to Add Product <a href="{% url 'seller:add-to-stock' %}">Add Product</a>
            </small>
        </p>

    </section>

</div>

<!--  -->
{% endblock content %}

SalesAssistant/Seller/templates/Seller/index.html
{% extends 'Seller/base.html' %} {% block title %} Home {% endblock title %}
<!--  -->
{% block content %}
<!--  -->
<div class="panel">
    {% for product in products %}
    <!--  -->
    {% if product.number_of_products%}
    <!--  -->
    <div>

        <p>{{product.product_name}} <span>
            <small id="type">{{product.product_type}}</small>
        </span></p>
        <hr id="panel-line">
        <!--  -->
        {% if product.image %}
        <img src="{{product.image.url}}" alt="Loading" height="150px" width="200px" />
        <span>{{product.number_of_products}}</span>
        <!--  -->
        {% endif %}
        <!--  -->
        <p>Amount: <strong>&cent;</strong><span style="text-decoration: underline;color:rgb(193, 193, 201) ;font-size: 22px;; "> {{product.price}}</span></p>
        <!--  -->
        <p>Manf. Date:<span>{{product.manuf_date}}</span></p>
        <!--  -->
        <p>Expire Date:<span>{{product.expire_date|date}}</span></p>
        <details>
            <a href="{% url 'seller:show-description' product.id %}" class="detailed-description">Full Description</a>
        </details>
        <span>
            <a id="btn-purchase" href="{% url 'seller:add-to-cart' product.id %}">Add To Cart</a>
        </span>

    </div>
    <!--  -->
    {%endif %}
    <!--  -->
    {% endfor %}
    <!--  -->
</div>
<!--  -->

{% endblock content %}

SalesAssistant/Seller/templates/Seller/myOrders.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %} profile{% endblock title %}
<!--  -->
{% block content %}

<!--  -->
<div class="my-ordered-items">
    {%for message in messages %}
    <!--  -->
    {{message}}
    <!--  -->
    {% endfor %}
    <section class="ordered-products">
        <div class="products-ordered">
            <table border="1" cellspacing="2">
                <tr>
                    <th>Product Name</th>
                    <th>Number</th>
                    <th>Unit Price</th>
                    <th>Action</th>
                </tr>
                {% for item in orders %}
                <!--  -->
                <tr>
                    <td style="text-transform: uppercase;">{{item.product}}</td>
                    <td>{{item.number}}</td>
                    <td>{{item.price}}</td>
                    <td>
                        <div class="action">
                            <a id="eidt-ordered" href="#">Edit</a>
                            <a id="remove-ordered" href="#">Remove</a>
                        </div>

                    </td>
                </tr>
                <!--  -->
                {% endfor %}
                <tr>
                    <th>Total</th>
                    <td id="total-price-info" colspan="3">{{total.total_price}}</td>
                </tr>
            </table>
        </div>
        <form action="{% url 'seller:my-orders' %}" class="buy-form" method="POST">
            {% csrf_token %}
            <div>
                <input type="text" name="customer_name" placeholder="Enter Your Name" required />
            </div>
            <div>
                <input type="email" name="customer_email" placeholder="Your Email" required>
            </div>
            <input type="submit" value="Buy" />
        </form>
    </section>
    <section class="orders">
        <a href="{% url 'seller:home' %}" id="order-more">Order More</a>
        <a href="{% url 'seller:clear-orders' %}" class="clear-orders">Clear Orders</a>

    </section>
</div>
<!--  -->
{% endblock content %}

SalesAssistant/Seller/templates/Seller/orders.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %}{% endblock title %}
<!--  -->
{% block content %}
<section class="purchase-product-info">
    <h3>Product Information</h3>
</section>
<div class="product-purchase-info">
    <section class="image-section">
        {% if product.image %}
        <img src="{{product.image.url}}" width="80px" height="100px" />
        <!--  -->
        {% endif %}
    </section>

    <section class="form-section">
        <form action="{% url 'seller:add-to-cart' product.id %}" method="POST">
            {% csrf_token %}
            <!--  -->
            <p>Product Name:</p>
            <!--  -->
            <input class="purchase-inputs" type="text" name="productName" value="{{product.product_name}}" disabled />
            <!--  -->
            <!--  -->
            <p>No. To Buy:</p>
            <!--  -->
            {% for message in messages %}
            <!--  -->
            <p>{{message}}</p>
            <!--  -->
            {% endfor %}
            <input class="purchase-inputs" type="number" name="number_to_buy" required />
            <!--  -->
            <p>Unit Amount:</p>
            <!--  -->
            <input class="purchase-inputs" type="number" name="price" value="{{product.price}}" disabled/>
            <!--  -->
            <input class="purchase-btn" type="submit" name="submit" value="Order" />
        </form>
    </section>

</div>
<!--  -->
<div class="decline">
    <a href="{% url 'seller:home' %}">Decline</a>
</div>

<!--  -->
{% endblock content %}

SalesAssistant/Seller/templates/Seller/profile.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %} profile{% endblock title %}
<!--  -->
{% block content %}

<!--  -->
<div class="profile-info">
    <div class="profile-header">
        <h1>In Profile</h1>
    </div>
    <h3>Products Added</h3>
    <div class="profile-items-info">

        {% for product in products %}
        <div class="profile-added-items">
            <p>{{product}}</p>
            <img src="{{product.image.url}}" width="220px" height="200px" />
            <div class="profile-item-action">
                <a href="{% url 'seller:edit_product' product.id %}" class="profile-edit-product-info">Edit</a>
                <a href="{% url 'seller:delete-item' product.id %}" class="profile-delete-item">Delete</a>
            </div>

        </div>
        <!--  -->
        {% endfor %}
        <!--  -->
    </div>

</div>

{% endblock content %}

SalesAssistant/Seller/templates/Seller/search_results.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %}Results{% endblock title %}
<!--  -->

{% block content%}
<!--  -->
<div class="panel">
    {% for product in products %}
    <!--  -->
    {% if product.number_of_products%}
    <!--  -->
    <div>
        <p>{{product.product_name}}</p>
        <hr>
        <!--  -->
        {% if product.image %}
        <img src="{{product.image.url}}" width="100px" height="105px" />
        <!--  -->
        {% endif %}
        <!--  -->
        <p>Amount: <strong>&cent;</strong><span style="text-decoration: underline;color:rgb(193, 193, 201) ;font-size:larger; "> {{product.price}}</span></p>
        <!--  -->
        <p>Manf. Date:<span>{{product.manuf_date}}</span></p>
        <!--  -->
        <p>Expire Date:<span>{{product.expire_date|date}}</span></p>
        <details>
            <a href="{% url 'seller:show-description' product.id %}">
                {{product.description}}
            </a>
        </details>
        <span>
            <a id="btn-purchase" href="{% url 'seller:add-to-cart' product.id %}">Add To Cart</a>
        </span>

    </div>
    <!--  -->
    {%endif %}
    <!--  -->
    {% empty %}
    <!--  -->
    <p>No Results Found For The Product with Name: <strong>{{item}}</strong></p>
    {% endfor %}
    <!--  -->
</div>

{% endblock content %}

SalesAssistant/Seller/templates/Seller/show_description.html
{% extends 'Seller/base.html' %}
<!--  -->
{% block title %} show description {% endblock title %}

<!--  -->
{% block content %}

<div class="description-img">
    <img src="{{product.image.url}}" alt="Loading " width="200px" height="150px" />
</div>
<p>
    {{product.description}}
</p>
<a id="btn-purchase" href="{% url 'seller:add-to-cart' product.id %}" class="back-to-buy">Add To Cart</a>
<!--  -->

{% endblock content %}